/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_cine;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.AdjustmentListener;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author familia medina
 */
public class Sillas extends javax.swing.JFrame {
   private int numero_sala ; 
   private int capacidad;
    
   int i=0, x=0, y=5 ,  j = 0, k = 0;
    String fila[];
    String colum[];
    String fi, co;
    int fil = 0;
    int col = 0;
    int nsalasa;
    JButton jButton1,jButton2;
    JPanel sillasn;



    public Sillas() {
 
        initComponents();
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void crear(){
        Container contenedor = getContentPane();
        contenedor.setLayout(new GridLayout(1,150));
        sillasn = new JPanel();
        sillasn.setBackground(Color.RED);
        jScrollPanel = new javax.swing.JScrollPane();
        
        int a1=0;
        int div;
          if(capacidad>10 && capacidad<31){
          div = 2;
          
          }
          if(capacidad<11){
          
          div = 1;
          
          }
          
          else{
          
          div = capacidad/10;    
          
          }
       sillasn.setLayout( new GridLayout(div,1));  
 
        while (j<capacidad){
            k=0;
            x=0;
        JButton jButton1 = new javax.swing.JButton();
        jButton1.setText(""+i);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(x, y, 100, 100);
            
        sillasn.add(jButton1);
    
        i++;
        x=x+100;
        k++;
            y= y+100;
            j++;
        }
        add(jScrollPanel, BorderLayout.CENTER);
        jScrollPanel.setViewportView(sillasn);
       
        i=0; 
        x=0; 
        y=5;  
        j = 0;
        k = 0;
        
        
    } 
    public void ejem(){
        
    }
           
      public void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
         i=0;
         while(i<capacidad){
         if(evt.getActionCommand().equals(""+i)){
       
        System.out.println(""+i);
           
        }
  
         i++;
         }
     }
      
    
 
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sillas().setVisible(true);
            }
        });
    }

    private javax.swing.JScrollPane jScrollPanel;
    private AdjustmentListener ajustar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
